name: nfc_card_presentation
description: Nfc Card Presentation Layer
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.7
  freezed_annotation: ^2.4.1
  nfc_card_data:
    path: ../nfc_card_data
  nfc_card_domain:
    path: ../nfc_card_domain
  go_router: ^11.1.2
  intl: ^0.18.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  freezed: ^2.4.3
  import_sorter: ^4.6.0
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0

flutter_gen:
  output: lib/src/core/assets
  line_length: 80

  # Optional
  integrations:
    flutter_svg: true
